# Generated by Django 3.2.18 on 2023-03-10 09:59

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=services.models.transaction_directory_path)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.transaction')),
            ],
        ),
    ]
